name: bmihealthy
description: New BMI Calcautor with suggetions
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_mobile_ads: ^4.0.0

  # UI Libraries
  adaptive_theme: ^3.4.1
  toastification: 1.0.2

  # Flutter Core
  dart_secure: ^0.5.40
  shared_preferences: ^2.2.2

  # Other
  url_launcher: ^6.1.14
  flutter_bloc: ^8.1.3

  #SaifAlmajd Packages
  device_preview: ^1.1.0
  flutter_launcher_icons: "^0.12.0"

#run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"




flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/BMI/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

        - asset: assets/fonts/Montserrat-Medium.ttf
          style: normal
          weight: 400

        - asset: assets/fonts/Montserrat-Light.ttf
          style: italic
          weight: 400